### ISSUE TITLE
TypeError: null is not an object (evaluating 'names.map')

### ISSUE THREAD

**Issue by Krapulat** [integer-net/magento2-requirejs-bundling#10]
After installing the M2.3.4 patch to a 2.3.5 store I get this JS error in frontend:
TypeError: null is not an object (evaluating 'names.map')

The line is:

`return typeof names !== 'string' ? names.map(processName) : processName(names);`

from vendor/magento/magento2-base/lib/web/mage/requirejs/mixins.js

EDIT: Solved

**Comment by wigman** [comment]
@Krapulat thanks for reporting that you fixed it.
Can you share what caused it? Others might benefit from your information.
