### ISSUE TITLE
this patch fixes for 2.3.4

### ISSUE THREAD

**Issue by secaliskan** [integer-net/magento2-requirejs-bundling#2]
Hi,
I just came to use baler for JS bundling :)
We upgraded to 2.3.4 few days ago. 
Is there need for this patch fixes for 2.3.4 also? Or with this version already fixed?

thanks in advance...

**Comment by wigman** [comment]
<strike>Hi. The patches ended up in 2.3.4, so you can remove them :)</strike>

update, I'm sorry: the patch for Mixins is not available in 2.3.4, so you still need that.
I'll update the repo and blog asap
