### ISSUE TITLE
Support for HTTP Auth

### ISSUE THREAD

**Issue by edward-simpson** [integer-net/magento2-requirejs-bundling#3]
All of our staging sites sit behind HTTP Auth, it'd be really handy if a username and password could be provided to the generate command to get around this!

**Comment by wigman** [comment]
Hi Edward.
To which generate command should it be added? All the commands are ran from command-line, so I'm not sure what HTTP auth you'd need...

**Comment by edward-simpson** [comment]
Sorry managed to add this to the wrong repo :D
