### ISSUE TITLE
Check patches needed for M2.3.5

### ISSUE THREAD

**Issue by wigman** [integer-net/magento2-requirejs-bundling#5]
Check whether the last patch is still needed for 2.3.5.
If anyone else has already checked/tested, please let me know.

**Comment by gaiterjones** [comment]
I've tested the 2.3.4 patch with 2.3.5-p1 as I was seeing errors without it but I am not 100% sure if it is still required.

**Comment by gjportegies** [comment]
I've experienced errors without the 2.3.4 patch as well on a 2.3.5-p1 instance. The `lib/web/mage/requirejs/mixins.js` is exactly the same in 2.3.4 and 2.3.5-p1.

- https://raw.githubusercontent.com/magento/magento2/2.3.4/lib/web/mage/requirejs/mixins.js
- https://raw.githubusercontent.com/magento/magento2/2.3.5-p1/lib/web/mage/requirejs/mixins.js

**Comment by WinstonN** [comment]
Do you think I need this patch if I'm running 2.3.5-p2 ?

**Comment by WinstonN** [comment]
nvm https://github.com/magesuite/magepack/issues/38#issuecomment-663043648 says I do need that patch

**Comment by wigman** [comment]
With 2.3.6 we have the first version that doesn't need patches anymore!
Therefore closing this issue
