### ISSUE TITLE
File could not be downloaded.

### ISSUE THREAD

**Issue by LucasMali** [integer-net/magento2-requirejs-bundling#7]
When following the README, I tried to get the patches for 2.3.3 (shims) applied but keep getting this error when running composer install; I'm currently on 2.3.3 patched.

`    
patches/composer/M233/github-pr-4721-base.diff ([Performance] Fix missing shims and phtml files with mage-init directives (https://github.com/magento/magento2/commit/db43c11c6830465b764ede32abb7262258e5f574))
   Could not apply patch! Skipping. The error was: The "patches/composer/M233/github-pr-4721-base.diff" file could not be downloaded: failed to open stream: No such file or directory
`

**Comment by wigman** [comment]
Hi. Please look at https://github.com/integer-net/magento2-requirejs-bundling/issues/4
