### ISSUE TITLE
Patches for 2.3.1 and 2.3.2 reference non-existent jquery-ui-modules

### ISSUE THREAD

**Issue by Leland** [integer-net/magento2-requirejs-bundling#8]
https://github.com/integer-net/magento2-requirejs-bundling/blob/f2a987a87b3892bf8f18bb429646548141164143/patches/composer/M232/github-pr-4721-base.diff#L18-L22

jquery-ui-modules wasn't actually created and released until Magento v2.3.3: 
https://github.com/magento/magento2/commit/fc7059fd5f9ef058338a3291817ae03ea471da03#diff-81856bdc345432427d0b347b770e3e96

Thus, on either version you'll currently get hit with this error:

```bash
Tracing dependencies for: requirejs/require

Tracing dependencies for: bundles/shared
Error: ENOENT: no such file or directory, open '/pub/static/frontend/Vendor/theme/en_US/jquery-ui-modules/widget.js'
In module tree:
    jquery/patches/jquery-ui

Error: Error: ENOENT: no such file or directory, open '/pub/static/frontend/Vendor/theme/en_US/jquery-ui-modules/widget.js'
In module tree:
    jquery/patches/jquery-ui

    at Object.openSync (fs.js:461:3)
```

**Comment by wigman** [comment]
Closing, not going to fix a version that is this old. Assuming it is no longer relevant

**Comment by Leland** [comment]
Well, this repo does actually talk about how to support v2.3.1 onwards in the readme: https://github.com/integer-net/magento2-requirejs-bundling#patches

If this project isn't planning on working on issues with that readme, can you delete those sections instead?

**Comment by wigman** [comment]
If I remove that particular patch, are you able to test it? (sorry if I closed the ticket pre-maturely, I wouldn't expect anyone still be using 2.3.1/2.32 today)
