### ISSUE TITLE
Is Patch broken is 2.3.5-p1 ?

### ISSUE THREAD

**Issue by adrianbsystems** [integer-net/magento2-requirejs-bundling#9]
Have carefully followed steps but cannot get the  patch ti install.
When we try with CE 2.3.5-p1, we get the output below, are we missing something ?

 composer update
Gathering patches for root package.
Removing package magento/magento2-base so that it can be re-installed and re-patched.
  - Removing magento/magento2-base (2.3.5-p1)
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
Gathering patches for root package.
Gathering patches for dependencies. This might take a minute.
  - Installing magento/magento2-base (2.3.5-p1): Loading from cache
  - Applying patches for magento/magento2-base
    patches/composer/M234/github-pr-25587-base.diff (Refactor JavaScript mixins module https://github.com/magento/magento2/pull/25587)
   Could not apply patch! Skipping. The error was: Cannot apply patch patches/composer/M234/github-pr-25587-base.diff

  [Exception]
  Cannot apply patch Refactor JavaScript mixins module https://github.com/magento/magento2/pull/25587 (patches/composer/M234/gi
  thub-pr-25587-base.diff)!

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

**Comment by wigman** [comment]
Hi Adrian. You can get a detailed error if you run composer with `-vvv`.

**Comment by adrianbsystems** [comment]
Perfect advice , that found the problem, stupidly it was new server and patch was not installed !

All working fine now, thanks very much.

**Comment by wigman** [comment]
Perfect, you’re welcome. Thanks for letting me know!
